package controllers;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import model.PaymentMethod;
// import GUI.SalesScreen;
import views.SalesScreen;

/**
 * The PaymentButtonsController class is an implementation of the ActionListener
 * interface.
 * It's responsible for handling button click events related to payment methods
 * in a retail application.
 * It overrides the actionPerformed method from the ActionListener interface.
 * This method is called when a button is clicked. It gets the action command of
 * the event,
 * checks if it's "cash", "visa", or "mobile", and if so, sets the payment
 * method accordingly.
 */
public class PaymentButtonsController implements ActionListener {

    /**
     * Handles button click events.
     * This method is called when a button is clicked. It gets the action command of
     * the event,
     * checks if it's "cash", "visa", or "mobile", and if so, sets the payment
     * method accordingly.
     *
     * @param e the ActionEvent object generated by the button click event.
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        String command = e.getActionCommand();
        switch (command) {
            case "cash":
                SalesScreen.setPaymentMethod(model.PaymentMethod.fromString("cash"));
                System.out.println("changing payment to: cash");
                break;
            case "visa":
                SalesScreen.setPaymentMethod(model.PaymentMethod.fromString("visa"));
                System.out.println("changing payment to: visa");
                break;
            case "mobile":
                SalesScreen.setPaymentMethod(model.PaymentMethod.fromString("mobile"));
                System.out.println("changing payment to: mobile");
                break;

            default:
                break;
        }
    }
}
